name: Test Matrix

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable --network-timeout 1000000


      - name: Run  Lint
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn lint
